/*-------------------------------------------------*/
/*----------------- 테이블 삭제 --------------------*/
/*-------------------------------------------------*/

DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE PORTFOLIO CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
DROP TABLE JJIM CASCADE CONSTRAINTS;
DROP TABLE REQUEST CASCADE CONSTRAINTS;
DROP TABLE CHATROOM CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE BIG_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE SUB_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE MEMBER_DIVIDE CASCADE CONSTRAINTS;
DROP TABLE GRADE CASCADE CONSTRAINTS;
DROP TABLE BOARD_DIVIDE CASCADE CONSTRAINTS;
DROP TABLE REPORT CASCADE CONSTRAINTS;
DROP TABLE SIDO CASCADE CONSTRAINTS;
DROP TABLE SIGUNGU CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MNO;    
DROP SEQUENCE SEQ_PNO;    
DROP SEQUENCE SEQ_REVNO;     
DROP SEQUENCE SEQ_REPNO;     
DROP SEQUENCE SEQ_BNO;    
DROP SEQUENCE SEQ_ATTNO;
DROP SEQUENCE SEQ_REQUESTNO;
DROP SEQUENCE SEQ_ROOMNO;
DROP SEQUENCE SEQ_MESSAGENO;
DROP SEQUENCE SEQ_BCATEGORYNO;
DROP SEQUENCE SEQ_SCATEGORYNO;
DROP SEQUENCE SEQ_REPORTNO;

/* 테이블 생성 */
/*-------------------------------------------------*/
/*------------------MEMBER-------------------------*/
/*-------------------------------------------------*/
CREATE TABLE MEMBER (
    USER_NO NUMBER NOT NULL PRIMARY KEY,
    EMAIL VARCHAR2(50) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(200) NOT NULL,
    USER_NAME VARCHAR2(51) NOT NULL,
    BIRTH VARCHAR2(6) NOT NULL,
    GENDER VARCHAR2(1),
    PHONE VARCHAR2(13) NOT NULL,
    ZIPCODE NUMBER NOT NULL,
    ADDRESS1 VARCHAR2(300) NOT NULL,
    ADDRESS2 VARCHAR2(300),
    ADDRESS3 VARCHAR2(300),
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONNECT_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')) ,
    MEMBER_DIVIDE_NO NUMBER CHECK (MEMBER_DIVIDE_NO IN('1','2','3'))NOT NULL,
    GRADE_NO NUMBER DEFAULT 200 CHECK (GRADE_NO IN('100','200','300','400')) ,
    BLACK_STATUS  VARCHAR2(1) DEFAULT 'N' CHECK (BLACK_STATUS IN('Y', 'N'))
);

COMMENT ON TABLE MEMBER IS '회원정보';
COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.BIRTH IS '생년월일';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.ZIPCODE IS '우편번호';
COMMENT ON COLUMN MEMBER.ADDRESS1 IS '주소1';
COMMENT ON COLUMN MEMBER.ADDRESS2 IS '주소2';
COMMENT ON COLUMN MEMBER.ADDRESS3 IS '주소3';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.CONNECT_DATE IS '최근접속일';
COMMENT ON COLUMN MEMBER.MEMBER_DIVIDE_NO IS '회원구분';
COMMENT ON COLUMN MEMBER.GRADE_NO IS '회원등급';
COMMENT ON COLUMN MEMBER.BLACK_STATUS IS '블랙리스트상태';
COMMENT ON COLUMN MEMBER.STATUS IS '회원상태';

CREATE SEQUENCE SEQ_MNO
NOCACHE;

/*-------------------------------------------------*/
/*------------------PORTFOLIO----------------------*/
/*-------------------------------------------------*/

CREATE TABLE PORTFOLIO (
    PTF_NO	NUMBER NOT NULL PRIMARY KEY,
    INTRODUCE VARCHAR2(900) NOT NULL,
    PTF_CONTENT	VARCHAR2(4000),
    SIGUNGU_NO NUMBER NOT NULL,
    CREATE_DATE	DATE DEFAULT SYSDATE NOT NULL ,
    MODIFY_DATE	DATE DEFAULT SYSDATE ,
    STATUS	VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    MTO_NO	NUMBER NOT NULL,
    SUBCATEGORY_NO	NUMBER NOT NULL
    
);
COMMENT ON TABLE PORTFOLIO IS '멘토포트폴리오';
COMMENT ON COLUMN PORTFOLIO.PTF_NO IS '포트폴리오번호';
COMMENT ON COLUMN PORTFOLIO.INTRODUCE IS '한줄소개';
COMMENT ON COLUMN PORTFOLIO.PTF_CONTENT IS '포트폴리오내용';
COMMENT ON COLUMN PORTFOLIO.SIGUNGU_NO IS '시군구번호';
COMMENT ON COLUMN PORTFOLIO.CREATE_DATE IS '작성일';
COMMENT ON COLUMN PORTFOLIO.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN PORTFOLIO.STATUS IS '포트폴리오상태';
COMMENT ON COLUMN PORTFOLIO.MTO_NO IS '멘토회원번호';
COMMENT ON COLUMN PORTFOLIO.CATEGORY_NO IS '소분류번호';

CREATE SEQUENCE SEQ_PNO
NOCACHE;

/*-------------------------------------------------*/
/*--------------------REVIEW-----------------------*/
/*-------------------------------------------------*/
CREATE TABLE REVIEW (
    REVIEW_NO NUMBER NOT NULL PRIMARY KEY,
    REVIEW_TITLE VARCHAR2(900) NOT NULL,
    REVIEW_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_DATE	DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE	DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    REF_PNO NUMBER NOT NULL,	
    USER_NO	NUMBER NOT NULL,
    SCORE NUMBER CHECK (SCORE BETWEEN 1 AND 5)
);

COMMENT ON TABLE REVIEW IS '멘토후기';
COMMENT ON COLUMN REVIEW.REVIEW_NO IS '리뷰번호';
COMMENT ON COLUMN REVIEW.REVIEW_TITLE IS '리뷰제목';
COMMENT ON COLUMN REVIEW.REVIEW_CONTENT IS '리뷰내용';
COMMENT ON COLUMN REVIEW.CREATE_DATE IS '작성날짜';
COMMENT ON COLUMN REVIEW.MODIFY_DATE IS '수정날짜';
COMMENT ON COLUMN REVIEW.STATUS IS '리뷰상태';
COMMENT ON COLUMN REVIEW.REF_PNO IS '포트폴리오 참조번호';
COMMENT ON COLUMN REVIEW.USER_NO IS '참조멘티회원번호';
COMMENT ON COLUMN REVIEW.SCORE IS '별점';

CREATE SEQUENCE SEQ_REVNO
NOCACHE;

/*-------------------------------------------------*/
/*---------------------REPLY-----------------------*/
/*-------------------------------------------------*/
CREATE TABLE REPLY(
    REPLY_NO NUMBER NOT NULL PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE	DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    USER_NO NUMBER NOT NULL,
    BOARD_NO NUMBER
);

COMMENT ON TABLE REPLY IS '댓글';
COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '작성날??';
COMMENT ON COLUMN REPLY.MODIFY_DATE IS '수정날짜';
COMMENT ON COLUMN REPLY.STATUS IS '댓글상태';
COMMENT ON COLUMN REPLY.USER_NO IS '작성유저번호';
COMMENT ON COLUMN REPLY.BOARD_NO IS '참조게시글번호';

CREATE SEQUENCE SEQ_REPNO
NOCACHE;

/*-------------------------------------------------*/
/*--------------------BOARD------------------------*/
/*-------------------------------------------------*/
CREATE TABLE BOARD(
    BOARD_NO NUMBER NOT NULL PRIMARY KEY,
    BOARD_TITLE	VARCHAR2(900) NOT NULL,   
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    COUNT NUMBER DEFAULT 0,
    CREATE_DATE	DATE DEFAULT SYSDATE NOT NULL,
    MODIFY_DATE	DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    USER_NO	NUMBER NOT NULL,
    BOARD_DIVIDE_NO	NUMBER NOT NULL CHECK (BOARD_DIVIDE_NO IN('10','20','40','50'))
);

COMMENT ON TABLE BOARD IS '커뮤니티및고객센터';
COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN BOARD.COUNT IS '조회수';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성날짜';
COMMENT ON COLUMN BOARD.MODIFY_DATE IS '수정날짜';
COMMENT ON COLUMN BOARD.STATUS IS '게시글상태';
COMMENT ON COLUMN BOARD.USER_NO IS '작성자';
COMMENT ON COLUMN BOARD.BOARD_DIVIDE_NO IS '게시글구분번호';

CREATE SEQUENCE SEQ_BNO
NOCACHE;

/*-------------------------------------------------*/
/*------------------ATTACHMENT---------------------*/
/*-------------------------------------------------*/
CREATE TABLE ATTACHMENT(
    FILE_NO	NUMBER NOT NULL PRIMARY KEY,
    ORIGIN_NAME	VARCHAR2(300) NOT NULL,
    CHANGE_NAME	VARCHAR2(300) NOT NULL,
    FILE_PATH VARCHAR2(2000),
    UPLOAD_DATE	DATE DEFAULT SYSDATE NOT NULL ,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    FILE_TYPE NUMBER NOT NULL CHECK (FILE_TYPE IN('1','2','3')),
    REF_BNO	NUMBER NOT NULL,
    FILE_LEVEL NUMBER
);

COMMENT ON TABLE ATTACHMENT IS '파일';
COMMENT ON COLUMN ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN ATTACHMENT.CHANGE_NAME IS '파일수정명';
COMMENT ON COLUMN ATTACHMENT.FILE_PATH IS '파일경로';
COMMENT ON COLUMN ATTACHMENT.UPLOAD_DATE IS '업로드날짜';
COMMENT ON COLUMN ATTACHMENT.STATUS IS '파일상태';
COMMENT ON COLUMN ATTACHMENT.FILE_TYPE IS '참조위치(1(게시글)/2(포트폴리오)/3)';
COMMENT ON COLUMN ATTACHMENT.REF_BNO IS '게시글참조용NO';
COMMENT ON COLUMN ATTACHMENT.FILE_LEVEL IS '1(프로필)/2(일반)';

CREATE SEQUENCE SEQ_ATTNO NOCACHE;

/*-------------------------------------------------*/
/*--------------------JJIM-------------------------*/
/*-------------------------------------------------*/
CREATE TABLE JJIM(
    MTO_NO NUMBER NOT NULL ,
    MTI_NO NUMBER NOT NULL,
    CONSTRAINT JJIM_PK PRIMARY KEY(MTO_NO,MTI_NO)
);
COMMENT ON TABLE JJIM IS '찜';
COMMENT ON COLUMN JJIM.MTO_NO IS '찜당한멘토회원번호';
COMMENT ON COLUMN JJIM.MTI_NO IS '찜한멘티회원번호';

/*-------------------------------------------------*/
/*--------------------REQUEST-------------------------*/
/*-------------------------------------------------*/

CREATE TABLE REQUEST(
    REQUEST_NO	NUMBER NOT NULL PRIMARY KEY,
    REQUEST_DATE DATE DEFAULT SYSDATE NOT NULL,
    REQUEST_CONTENT VARCHAR2(3000) NOT NULL,
    STATUS	VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    REQUEST_STATUS VARCHAR2(1) DEFAULT 'W' CHECK (REQUEST_STATUS IN('Y', 'W', 'N')),
    MTI_NO	NUMBER NOT NULL,
    MTO_NO	NUMBER NOT NULL
);
COMMENT ON TABLE REQUEST IS '멘토요청';
COMMENT ON COLUMN REQUEST.REQUEST_NO IS '요청번호';
COMMENT ON COLUMN REQUEST.REQUEST_DATE IS '요청날짜';
COMMENT ON COLUMN REQUEST.STATUS IS '요청상태';
COMMENT ON COLUMN REQUEST.REQUEST_STATUS IS '수락상태';
COMMENT ON COLUMN REQUEST.MTI_NO IS '요청한멘티번호';
COMMENT ON COLUMN REQUEST.MTO_NO IS '요청받은멘토번호';

CREATE SEQUENCE SEQ_REQUESTNO
NOCACHE;

/*-------------------------------------------------*/
/*--------------------CHATROOM---------------------*/
/*-------------------------------------------------*/
CREATE TABLE CHATROOM(
    ROOM_NO	NUMBER NOT NULL PRIMARY KEY,
    ROOM_DATE  DATE DEFAULT SYSDATE NOT NULL,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
    MTI_NO NUMBER NOT NULL,
    MTO_NO NUMBER NOT NULL
);
COMMENT ON TABLE CHATROOM IS '채팅방';
COMMENT ON COLUMN CHATROOM.ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHATROOM.ROOM_DATE IS '생성날짜';
COMMENT ON COLUMN CHATROOM.STATUS IS '채팅방상태';
COMMENT ON COLUMN CHATROOM.MTI_NO IS '멘티회원번호';
COMMENT ON COLUMN CHATROOM.MTO_NO IS '멘토회원번호';

CREATE SEQUENCE SEQ_ROOMNO
NOCACHE;

/*-------------------------------------------------*/
/*------------------MESSAGE------------------------*/
/*-------------------------------------------------*/
CREATE TABLE MESSAGE(
    MESSAGE_NO NUMBER NOT NULL PRIMARY KEY,
    MESSAGE_CONTENT	VARCHAR2(4000) NOT NULL,
    MESSAGE_DATE DATE DEFAULT SYSDATE NOT NULL,
    STATUS	VARCHAR2(1) DEFAULT 'Y'  CHECK (STATUS IN('Y', 'N')),
    ROOM_NO	NUMBER NOT NULL
);
COMMENT ON TABLE MESSAGE IS '메세지';
COMMENT ON COLUMN MESSAGE.MESSAGE_NO IS '메세지번호';
COMMENT ON COLUMN MESSAGE.MESSAGE_CONTENT IS '메세지내용';
COMMENT ON COLUMN MESSAGE.MESSAGE_DATE IS '보낸시간';
COMMENT ON COLUMN MESSAGE.STATUS IS '확인여부';
COMMENT ON COLUMN MESSAGE.ROOM_NO IS '참조채팅방번호';

CREATE SEQUENCE SEQ_MESSAGENO
NOCACHE;

/*-------------------------------------------------*/
/*------------------BIG_CATEGORY-------------------*/
/*-------------------------------------------------*/
CREATE TABLE BIG_CATEGORY (
    CATEGORY_NO	NUMBER NOT NULL PRIMARY KEY,
   CATEGORY_NAME VARCHAR2(100) NOT NULL
);
COMMENT ON TABLE BIG_CATEGORY IS '대분류';
COMMENT ON COLUMN BIG_CATEGORY.CATEGORY_NO IS '대분류번호';
COMMENT ON COLUMN BIG_CATEGORY.CATEGORY_NAME IS '대분류이름';

CREATE SEQUENCE SEQ_BCATEGORYNO
NOCACHE;

/*-------------------------------------------------*/
/*------------------SUB_CATEGORY-------------------*/
/*-------------------------------------------------*/
CREATE TABLE SUB_CATEGORY (
    SUBCATEGORY_NO	NUMBER NOT NULL PRIMARY KEY,
    SUBCATEGORY_NAME VARCHAR2(100) NOT NULL,
    REF_CATEGORY_NO NUMBER NOT NULL
);
COMMENT ON TABLE SUB_CATEGORY IS '소분류';
COMMENT ON COLUMN SUB_CATEGORY.SUBCATEGORY_NO IS '소분류번호';
COMMENT ON COLUMN SUB_CATEGORY.SUBCATEGORY_NAME IS '소분류이름';
COMMENT ON COLUMN SUB_CATEGORY.REF_CATEGORY_NO IS '참조대분류번호';

CREATE SEQUENCE SEQ_SCATEGORYNO
NOCACHE;

/*-------------------------------------------------*/
/*------------------MEMBER_DIVIDE------------------*/
/*-------------------------------------------------*/
CREATE TABLE MEMBER_DIVIDE(
MEMBER_DIVIDE_NO NUMBER NOT NULL PRIMARY KEY,
MEMBER_DIVIDE_NAME VARCHAR2(100) NOT NULL
);
COMMENT ON TABLE MEMBER_DIVIDE IS '회원구분';
COMMENT ON COLUMN MEMBER_DIVIDE.MEMBER_DIVIDE_NO IS '회원구분번호';
COMMENT ON COLUMN MEMBER_DIVIDE.MEMBER_DIVIDE_NAME IS '회원구분명';

/*-------------------------------------------------*/
/*---------------------GRADE-----------------------*/
/*-------------------------------------------------*/
CREATE TABLE GRADE (
    GRADE_NO NUMBER NOT NULL PRIMARY KEY,
    GRADE_NAME VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE GRADE IS '회원등급';
COMMENT ON COLUMN GRADE.GRADE_NO IS '회원등급번호';
COMMENT ON COLUMN GRADE.GRADE_NAME IS '회원등급명';

/*-------------------------------------------------*/
/*--------------------BOARD_DIVIDE-----------------*/
/*-------------------------------------------------*/
CREATE TABLE BOARD_DIVIDE(
    BOARD_DIVIDE_NO	NUMBER NOT NULL PRIMARY KEY,
    BOARD_DIVIDE_NAME VARCHAR2(30) NOT NULL
);
COMMENT ON TABLE BOARD_DIVIDE IS '게시글구분';
COMMENT ON COLUMN BOARD_DIVIDE.BOARD_DIVIDE_NO IS '게시글구분번호';
COMMENT ON COLUMN BOARD_DIVIDE.BOARD_DIVIDE_NAME IS '게시글구분명';

/*-------------------------------------------------*/
/*--------------------REPORT------------------------*/
/*-------------------------------------------------*/
CREATE TABLE REPORT(
    REPORT_NO NUMBER NOT NULL PRIMARY KEY,
    REPORT_CONTENT	VARCHAR2(4000) NOT NULL,
    REPORT_DATE DATE DEFAULT SYSDATE NOT NULL ,
    USER_NO	NUMBER NOT NULL,
    REF_USER_NO NUMBER,
    REF_REPLY_NO NUMBER,
    REF_BNO	NUMBER,
    STATUS	VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);
COMMENT ON TABLE REPORT IS '신고내역';
COMMENT ON COLUMN REPORT.REPORT_NO IS '신고번호';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고내용';
COMMENT ON COLUMN REPORT.REPORT_DATE IS '신고날짜';
COMMENT ON COLUMN REPORT.USER_NO IS '신고한 회원번호';
COMMENT ON COLUMN REPORT.REF_USER_NO IS '신고당한 회원번호';
COMMENT ON COLUMN REPORT.REF_REPLY_NO IS '신고당한 댓글번호';
COMMENT ON COLUMN REPORT.REF_BNO IS '신고당한 게시글번호';
COMMENT ON COLUMN REPORT.STATUS IS '신고상태';

CREATE SEQUENCE SEQ_REPORTNO
NOCACHE;

/*-------------------------------------------------*/
/*--------------------SIDO------------------------*/
/*-------------------------------------------------*/

CREATE TABLE SIDO (
    SIDO_NO NUMBER PRIMARY KEY,
    SIDO_NAME VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN SIDO.SIDO_NO IS '시도번호';
COMMENT ON COLUMN SIDO.SIDO_NAME IS '시도이름';

/*-------------------------------------------------*/
/*--------------------SIGUNGU----------------------*/
/*-------------------------------------------------*/

CREATE TABLE SIGUNGU (
    SIGUNGU_NO NUMBER PRIMARY KEY,
    SIGUNGU_NAME VARCHAR2(50),
    SIDO_NO NUMBER,
    FOREIGN KEY (SIDO_NO) REFERENCES SIDO(SIDO_NO)
);

COMMENT ON COLUMN SIGUNGU.SIGUNGU_NO IS '시군구번호';
COMMENT ON COLUMN SIGUNGU.SIGUNGU_NAME IS '시군구이름';
COMMENT ON COLUMN SIGUNGU.SIDO_NO IS '참조시도번호';

/*========================================================*/

/*소분류 외래키 설정*/
ALTER TABLE SUB_CATEGORY ADD CONSTRAINT FK_REF_CATEGORY_NO FOREIGN KEY(REF_CATEGORY_NO) REFERENCES BIG_CATEGORY(CATEGORY_NO);

/*MEMBER 외래키설정*/
ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER_DIVIDE_NO FOREIGN KEY(MEMBER_DIVIDE_NO) REFERENCES MEMBER_DIVIDE(MEMBER_DIVIDE_NO);
ALTER TABLE MEMBER ADD CONSTRAINT FK_GRADE_NO FOREIGN KEY(GRADE_NO) REFERENCES GRADE(GRADE_NO);

/*PORTFOLIO 외래키설정*/
ALTER TABLE PORTFOLIO ADD CONSTRAINT FK_MTO_NO FOREIGN KEY(MTO_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE PORTFOLIO ADD CONSTRAINT FK_SUBCATEGORY_NO FOREIGN KEY(SUBCATEGORY_NO) REFERENCES SUB_CATEGORY(SUBCATEGORY_NO);

/*REPORT 외래키설정*/
ALTER TABLE REPORT ADD CONSTRAINT FK_RP_USER_NO FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE REPORT ADD CONSTRAINT FK_RP_REPLY_NO FOREIGN KEY(REPLY_NO) REFERENCES REPLY(REPLY_NO);
ALTER TABLE REPORT ADD CONSTRAINT FK_RP_BOARD_DIVIDE_NO FOREIGN KEY(BOARD_DIVIDE_NO) REFERENCES BOARD_DIVIDE(BOARD_DIVIDE_NO);

/*MESSAGE 외래키설정*/
ALTER TABLE MESSAGE ADD CONSTRAINT FK_ME_ROOM_NO FOREIGN KEY(ROOM_NO) REFERENCES CHATROOM(ROOM_NO);

/*CHATROOM 외래키 설정*/
ALTER TABLE CHATROOM ADD CONSTRAINT FK_CH_MTI_NO FOREIGN KEY(MTI_NO) REFERENCES MEMBER(USER_NO);

/*REQUEST 외래키설정*/
ALTER TABLE REQUEST ADD CONSTRAINT FK_CL_MTI_NO FOREIGN KEY(MTI_NO) REFERENCES MEMBER(USER_NO);

/*JJIM 외래키설정*/
ALTER TABLE JJIM ADD CONSTRAINT FK_JJ_MTO_NO FOREIGN KEY(MTO_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE JJIM ADD CONSTRAINT FK_JJ_MTI_NO FOREIGN KEY(MTI_NO) REFERENCES MEMBER(USER_NO);

/*BOARD 외래키설정*/
ALTER TABLE BOARD ADD CONSTRAINT FK_USER_NO FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARDDIVIDE_NO FOREIGN KEY(BOARD_DIVIDE_NO) REFERENCES BOARD_DIVIDE(BOARD_DIVIDE_NO);

/*REPLY 외래키설정*/
ALTER TABLE REPLY ADD CONSTRAINT FK_BOARD_NO FOREIGN KEY(BOARD_NO) REFERENCES BOARD(BOARD_NO);

/*REVIEW 외래키설정*/
ALTER TABLE REVIEW ADD CONSTRAINT FK_MTI_NO FOREIGN KEY(USER_NO) REFERENCES MEMBER(USER_NO);
ALTER TABLE REVIEW ADD CONSTRAINT FK_REF_PNO FOREIGN KEY(REF_PNO) REFERENCES PORTFOLIO(PTF_NO);

COMMIT;