/*포트폴리오*/
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '3대 600, 허벅지 둘레만 36인치 최강 스쿼트', '하체 위주의 헬스로 당신의 허벅지를 불태워 드립니다. 우리모두 건강해지세요', 3, SYSDATE, SYSDATE, 'Y',2,1);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '강남역 제일 요가. 당신의 신체를 유연하게', '인도가서 요가 배워왔습니다. 피리불면 코브라도 춤추게해요', 52, SYSDATE, SYSDATE, 'Y',3,2);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '100미터 달리기 8초컷 찍습니다. 당신도 할 수 있어요.', '제가 어린이 보호구역에서 달리기하면 시속 50키로미터 찍혀서 과속카메라에 단속당합니다. 여러분도 할 수 있어요. 같이 달려봅시다.', 22, SYSDATE, SYSDATE, 'Y',4,4);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '엄랭 마스터.', '엄랭만 10년 했습니다. 이제는 대세가 될 엄랭 같이 배워보아요.',88, SYSDATE, SYSDATE, 'Y',5,46);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '국가대표출신 당신도 국가대표로 만들어 드리겠습니다.', '국가대표만이 들어갈 수 있는 태릉선수촌에서 많은 것들을 배워왔습니다. 저와 함께한다면 당신도 국가대표가 될 수 있습니다.',65, SYSDATE, SYSDATE, 'Y',6,24);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',7,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',8,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',9,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',10,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',11,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',12,51);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',13,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',14,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',15,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',31,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',32,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',33,51);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',34,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',35,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',36,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',37,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',39,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',39,51);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',7,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',8,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',9,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',10,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',11,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',12,51);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',13,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',14,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',15,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',31,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',32,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',33,51);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',34,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',35,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',36,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',37,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',39,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',40,1);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',15,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',31,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',32,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',33,51);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',34,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',35,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',36,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',37,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',39,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',40,1);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',41,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',42,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',43,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',44,51);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',45,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',46,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',47,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',48,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',49,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',50,1);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',57,2);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',51,4);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',52,46);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',53,27);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',34, SYSDATE, SYSDATE, 'Y',54,47);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',22, SYSDATE, SYSDATE, 'Y',55,18);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',23, SYSDATE, SYSDATE, 'Y',56,29);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',88, SYSDATE, SYSDATE, 'Y',58,39);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',77, SYSDATE, SYSDATE, 'Y',59,15);
INSERT INTO PORTFOLIO
VALUES (SEQ_PNO.NEXTVAL, '저 이거 좀 잘합니다.', '같이 해보아요',66, SYSDATE, SYSDATE, 'Y',60,1);


/*멘토후기*/
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 짱 친절', '정말 친절해요. 최고의 운동이였습니다. 근데 과다 운동으로 허벅지 근육 파열돼서 별점은 1점 드립니다.', SYSDATE, NULL,'Y',1,17,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '혼자 요가하려니 자세도 모르고 해서 힘들었', '는데 맨토님 만나고 같이 요가하면서 많은 것들을 배우고 또 즐길 수 있었습니다. 감사합니다.', SYSDATE, NULL,'Y',2,18,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '어제 과속으로 벌금 날라왔습니다', '맨토님이랑 같이 달리기 하다가 결국 시속 40키로미터로 과속카메라에 단속되었네요... 맨토님이랑 같이하면 달리기 실력 월등히 상승합니다. 짱', SYSDATE, NULL,'Y',3,17,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '엄랭 독학하려니 참 막막했는데..', '이런 언어를 십년동안 공부한 은둔고수가 있었네요. 덕분에 엄랭 마스터 했습니다. 근데 이걸 어디다 써야할진 모르겠네요 암튼 감사', SYSDATE, NULL,'Y',4,19,3);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '덕분에 국대 되었습니다', '맨토님 덕분에 이번 국대 뽑혔습니다. 감사합니다. 전 자랑하러 가야해서 이만..', SYSDATE, NULL,'Y',5,20,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',6,21,3);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',7,22,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',8,27,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',9,18,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',10,19,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',11,20,3);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',12,20,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 짱 친절', '정말 친절해요. 최고의 운동이였습니다. 근데 과다 운동으로 허벅지 근육 파열돼서 별점은 1점 드립니다.', SYSDATE, NULL,'Y',1,21,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '혼자 요가하려니 자세도 모르고 해서 힘들었', '는데 맨토님 만나고 같이 요가하면서 많은 것들을 배우고 또 즐길 수 있었습니다. 감사합니다.', SYSDATE, NULL,'Y',2,22,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '어제 과속으로 벌금 날라왔습니다', '맨토님이랑 같이 달리기 하다가 결국 시속 40키로미터로 과속카메라에 단속되었네요... 맨토님이랑 같이하면 달리기 실력 월등히 상승합니다. 짱', SYSDATE, NULL,'Y',3,23,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '엄랭 독학하려니 참 막막했는데..', '이런 언어를 십년동안 공부한 은둔고수가 있었네요. 덕분에 엄랭 마스터 했습니다. 근데 이걸 어디다 써야할진 모르겠네요 암튼 감사', SYSDATE, NULL,'Y',4,24,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '덕분에 국대 되었습니다', '맨토님 덕분에 이번 국대 뽑혔습니다. 감사합니다. 전 자랑하러 가야해서 이만..', SYSDATE, NULL,'Y',5,25,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',1,26,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',2,17,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',3,18,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',5,19,3);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',5,20,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',11,21,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',12,22,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',6,26,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',7,17,3);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',8,18,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',9,19,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',10,20,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',11,21,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',12,22,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',13,26,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',12,17,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',13,18,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',14,19,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',15,20,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',16,21,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',17,22,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',18,26,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',19,17,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',20,18,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',21,19,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',22,20,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',23,21,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',24,22,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',25,26,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',26,17,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',27,18,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',28,19,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',29,20,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',30,21,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',31,22,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',32,26,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',33,17,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',34,18,5);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',35,19,2);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',36,20,1);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',37,21,4);
INSERT INTO REVIEW
VALUES (SEQ_REVNO.NEXTVAL, '맨토님 보세요', '잘 알려주셔서 감삼다', SYSDATE, NULL,'Y',38,22,5);

INSERT INTO JJIM
VALUES (2, 18);
INSERT INTO JJIM
VALUES (2, 19);
INSERT INTO JJIM
VALUES (2, 20);
INSERT INTO JJIM
VALUES (2, 21);
INSERT INTO JJIM
VALUES (3, 18);
INSERT INTO JJIM
VALUES (3, 19);
INSERT INTO JJIM
VALUES (3, 20);
INSERT INTO JJIM
VALUES (3, 21);
INSERT INTO JJIM
VALUES (4, 18);
INSERT INTO JJIM
VALUES (4, 19);
INSERT INTO JJIM
VALUES (4, 20);
INSERT INTO JJIM
VALUES (4, 21);
INSERT INTO JJIM
VALUES (5, 18);
INSERT INTO JJIM
VALUES (5, 19);
INSERT INTO JJIM
VALUES (5, 20);
INSERT INTO JJIM
VALUES (5, 21);
INSERT INTO JJIM
VALUES (6, 18);
INSERT INTO JJIM
VALUES (6, 19);
INSERT INTO JJIM
VALUES (6, 20);
INSERT INTO JJIM
VALUES (6, 21);
INSERT INTO JJIM
VALUES (7, 18);
INSERT INTO JJIM
VALUES (7, 19);
INSERT INTO JJIM
VALUES (7, 20);
INSERT INTO JJIM
VALUES (7, 21);
INSERT INTO JJIM
VALUES (8, 18);
INSERT INTO JJIM
VALUES (8, 19);
INSERT INTO JJIM
VALUES (8, 20);
INSERT INTO JJIM
VALUES (8, 21);

COMMIT;